# -*- coding: utf-8 -*-
"""Módulos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UgNSMQ1HvXh_TL1nwwWCAf_Iq2xT1nh5
"""

import drive.MyDrive.libs.libFib
libFib.fib (100000)

import math
for x in range (1,20):
  print(math.log10(x))

from math import log10
for x in range (1,20):
  print(log10(x))

